<?php

declare(strict_types=1);

require_once __DIR__ . '/config/bootstrap.php';
require_once APP_ROOT . '/config/database.php';
require_once APP_ROOT . '/includes/auth.php';
if (auth_current_user() !== null) { header('Location: /', true, 302); exit; }
web_security_headers();
$escape = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b2638"><meta name="csrf-token" content="<?= $escape(auth_csrf_token()) ?>"><title>Criar conta — Hidra R3B</title><link rel="stylesheet" href="/static/css/auth.css"><script defer src="/static/js/auth.js"></script></head>
<body><main class="auth-layout"><section class="auth-brand-panel"><a class="auth-brand" href="/" aria-label="Hidra R3B"><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2S5.5 9 5.5 14.5a6.5 6.5 0 0 0 13 0C18.5 9 12 2 12 2Z"/></svg></span><strong>Hidra <b>R3B</b></strong></a><div><p class="eyebrow">Conta pessoal e segura</p><h1>Comece a monitorar em minutos.</h1><p>Crie sua conta, conecte o código seguro do equipamento e acompanhe apenas os seus reservatórios.</p></div><div class="brand-feature"><span>✓</span><p><strong>Dados separados por proprietário</strong><small>Leituras, gráficos e alertas ficam vinculados à sua conta.</small></p></div></section>
<section class="auth-form-panel"><div class="auth-card"><div class="mobile-brand">Hidra <b>R3B</b></div><p class="eyebrow">Primeiro acesso</p><h2>Crie sua conta</h2><p class="auth-subtitle">Use seus dados para acessar a central.</p><form class="auth-form" id="register-form" data-endpoint="/api/auth/register.php" data-success="redirect"><label><span>Nome</span><input name="name" type="text" minlength="2" maxlength="120" autocomplete="name" placeholder="Seu nome" required></label><label><span>E-mail</span><input name="email" type="email" maxlength="254" autocomplete="email" placeholder="voce@empresa.com" required></label><label><span>Senha</span><input name="password" type="password" minlength="10" maxlength="128" autocomplete="new-password" aria-describedby="password-hint" required><small id="password-hint">Mínimo de 10 caracteres, com letras e números.</small></label><label><span>Confirmar senha</span><input name="password_confirmation" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><p class="form-error" data-form-error role="alert"></p><button class="auth-submit" type="submit"><span>Criar conta</span><span class="button-loader" aria-hidden="true"></span></button></form><p class="auth-switch">Já possui uma conta? <a href="/login">Entrar</a></p></div><p class="auth-footer">Ao criar a conta, você concorda com o uso seguro dos dados para monitoramento.</p></section></main></body></html>
